# Generated by Django 3.2.15 on 2022-08-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_mains_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mains', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planner.mains')),
                ('starches', models.ManyToManyField(to='planner.Starch')),
                ('vegies', models.ManyToManyField(to='planner.Vegetable')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_week', models.DateField()),
                ('day_friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_friday', to='planner.meal')),
                ('day_monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_monday', to='planner.meal')),
                ('day_saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_saturday', to='planner.meal')),
                ('day_sunday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_sunday', to='planner.meal')),
                ('day_thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_thursday', to='planner.meal')),
                ('day_tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tuesday', to='planner.meal')),
                ('day_wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_wednesday', to='planner.meal')),
            ],
        ),
    ]
