# Generated by Django 3.2.15 on 2022-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_meal_mealplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='salad',
            field=models.ManyToManyField(to='planner.Salad'),
        ),
    ]
