# Generated by Django 3.2.15 on 2022-08-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20220822_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
