# Generated by Django 3.2.15 on 2022-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20220823_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='complete',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'Started'), (0, 'Not Started')], default=2),
        ),
    ]
