# Generated by Django 3.2.15 on 2022-08-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_mealplan_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='mains',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planner.mains'),
        ),
    ]
